name: Benchmark resources usage

on:
  # push:
  #   branches: ["master"]
  #   paths:
  #     - "src/**"
  # pull_request:
  #   branches: ["master"]
  #   paths:
  #     - "src/**"
  workflow_dispatch:

jobs:
  hot-storage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Run benchmark (memory)
        run: make dist && node --expose-gc benchmark/memory/benchmark.mjs hot-storage

      - name: Run benchmark (cpu)
        run: make dist && node --expose-gc benchmark/cpu/benchmark.mjs hot-storage

      - name: Run benchmark (speed)
        run: make dist && node --expose-gc benchmark/speed/benchmark.mjs hot-storage

      - name: Run benchmark (gc)
        run: make dist && node --expose-gc benchmark/gc/benchmark.mjs hot-storage

  redis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        redis-version: [6]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Wait for redis
        timeout-minutes: 5
        run: |
          while ! node -p -e "r=require('ioredis');c=new r(6379,process.env.REDIS_HOST);c.on('error', ()=>c.disconnect());c.ping().catch(()=>process.exit(1)).finally(()=>c.disconnect())"; do
            sleep 1
          done

      - name: Run benchmark (memory)
        run: |
          make dist && node --expose-gc benchmark/memory/benchmark.mjs redis


      - name: Run benchmark (cpu)
        run: |
          make dist && node --expose-gc benchmark/cpu/benchmark.mjs redis


      - name: Run benchmark (speed)
        run: |
          make dist && node --expose-gc benchmark/speed/benchmark.mjs redis


      - name: Run benchmark (gc)
        run: |
          make dist && node --expose-gc benchmark/gc/benchmark.mjs redis

